version: "3.9"
services:
  db:
    image: mysql:8
    container_name: demo-db
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
  #  ports:
  #    - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build:
      context: /home/nao/desarrollo/projects/SpringBoot/Mis_usuarios_local_plande_pagos
      dockerfile: Dockerfile
    container_name: demo-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: /home/nao/desarrollo/projects/react/prestamoscliente
      dockerfile: Dockerfile
    container_name: demo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
