services:
  backend:
    build:
      context: ./backend
    image: lab/backend:1.0.0
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=demo
      - SPRING_DATASOURCE_PASSWORD=demo123

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: /api
    image: lab/frontend:1.0.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

